### ISSUE TITLE
may iu help

### ISSUE THREAD

**Issue by Narulacodes** [SkylarkStudios/skylarkstudios.github.io#1]

**Comment by amazinigmech2418** [comment]
Sorry. You have to be in the SkylarkStudios collaborations on Scratch first.

**Comment by amazinigmech2418** [comment]
We did actually use GHStatus from Mountio for this though... You can ask @SkyanSam (SuperSamuel25MC on Scratch) to join.

**Comment by Narulacodes** [comment]
@amazinigmech2418  Invited to gitcowor.

Why diud you use itm it was for MOUNTIO. you should have asked me mech.
